name: "Publish"

on:
  release:
    types: [created, published]

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v1
      - name: Use Node.js v18
        uses: actions/setup-node@v1
        with:
          node-version: 18
      - name: Install Packages
        run: yarn install
      - name: Publish
        uses: JS-DevTools/npm-publish@v1
        with:
          access: 'public'
          token: ${{ secrets.NPM_PUBLISH_TOKEN }}
